//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenReloaded2.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeenReloaded2.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_acquired {
            get {
                object obj = ResourceManager.GetObject("gem_acquired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_blue1 {
            get {
                object obj = ResourceManager.GetObject("gem_blue1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_blue2 {
            get {
                object obj = ResourceManager.GetObject("gem_blue2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_green1 {
            get {
                object obj = ResourceManager.GetObject("gem_green1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_green2 {
            get {
                object obj = ResourceManager.GetObject("gem_green2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_blue_empty {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_blue_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_blue_filled {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_blue_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_green_empty {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_green_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_green_filled {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_green_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_red_empty {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_red_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_red_filled {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_red_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_yellow_empty {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_yellow_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_placeholder_yellow_filled {
            get {
                object obj = ResourceManager.GetObject("gem_placeholder_yellow_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_red1 {
            get {
                object obj = ResourceManager.GetObject("gem_red1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_red2 {
            get {
                object obj = ResourceManager.GetObject("gem_red2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_yellow1 {
            get {
                object obj = ResourceManager.GetObject("gem_yellow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_yellow2 {
            get {
                object obj = ResourceManager.GetObject("gem_yellow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventory_blue_gem {
            get {
                object obj = ResourceManager.GetObject("inventory_blue_gem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventory_green_gem {
            get {
                object obj = ResourceManager.GetObject("inventory_green_gem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventory_yellow_gem {
            get {
                object obj = ResourceManager.GetObject("inventory_yellow_gem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_air_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_air_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_air_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_air_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_air_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_air_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_platform_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_platform_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_platform_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_platform_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_platform_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_platform_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom1 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom2 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom3 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom4 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom5 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom6 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_bottom7 {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_bottom7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_cave_wall_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_cave_wall_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_platform_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_platform_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_platform_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_platform_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_platform_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_platform_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_platform_single {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_platform_single", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_wall_bottom1 {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_wall_bottom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_wall_bottom2 {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_wall_bottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_wall_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_wall_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_wall_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_wall_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_forest_wall_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_forest_wall_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_floor_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_floor_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform_single {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform_single", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform1 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform2 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform3 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_platform4 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_platform4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_bottom1 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_bottom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_bottom2 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_bottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_bottom3 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_bottom3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_bottom4 {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_bottom4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_mirage_wall_to_platform_right {
            get {
                object obj = ResourceManager.GetObject("keen4_mirage_wall_to_platform_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platform_horizontal_left1 {
            get {
                object obj = ResourceManager.GetObject("keen4_platform_horizontal_left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platform_horizontal_left2 {
            get {
                object obj = ResourceManager.GetObject("keen4_platform_horizontal_left2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platform_horizontal_right1 {
            get {
                object obj = ResourceManager.GetObject("keen4_platform_horizontal_right1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platform_horizontal_right2 {
            get {
                object obj = ResourceManager.GetObject("keen4_platform_horizontal_right2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platform_vertical1 {
            get {
                object obj = ResourceManager.GetObject("keen4_platform_vertical1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platform_vertical2 {
            get {
                object obj = ResourceManager.GetObject("keen4_platform_vertical2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_platorm_stationary {
            get {
                object obj = ResourceManager.GetObject("keen4_platorm_stationary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_wall_bottom1 {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_wall_bottom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_wall_bottom2 {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_wall_bottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_wall_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_wall_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_wall_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_wall_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_pyramid_wall_middle {
            get {
                object obj = ResourceManager.GetObject("keen4_pyramid_wall_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_left_edge_filled {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_left_edge_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_left_edge_filled_pyramid {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_left_edge_filled_pyramid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_left_edge_pyramid {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_left_edge_pyramid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_right_edge_filled {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_right_edge_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_right_edge_filled_pyramid {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_right_edge_filled_pyramid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_removable_platform_right_edge_pyramid {
            get {
                object obj = ResourceManager.GetObject("keen4_removable_platform_right_edge_pyramid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_rocket_propelled_platform1 {
            get {
                object obj = ResourceManager.GetObject("keen4_rocket_propelled_platform1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_rocket_propelled_platform2 {
            get {
                object obj = ResourceManager.GetObject("keen4_rocket_propelled_platform2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_rocket_propelled_platform3 {
            get {
                object obj = ResourceManager.GetObject("keen4_rocket_propelled_platform3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_rocket_propelled_platform4 {
            get {
                object obj = ResourceManager.GetObject("keen4_rocket_propelled_platform4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_secret_platform1 {
            get {
                object obj = ResourceManager.GetObject("keen4_secret_platform1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_secret_platform2 {
            get {
                object obj = ResourceManager.GetObject("keen4_secret_platform2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen4_secret_platform3 {
            get {
                object obj = ResourceManager.GetObject("keen4_secret_platform3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_black_floor_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen5_black_floor_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_black_wall_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen5_black_wall_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_ceiling_green {
            get {
                object obj = ResourceManager.GetObject("keen5_ceiling_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_ceiling_red {
            get {
                object obj = ResourceManager.GetObject("keen5_ceiling_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_black_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_black_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_black_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_black_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_black_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_black_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_green_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_green_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_green_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_green_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_green_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_green_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_red_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_red_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_red_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_red_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_floor_red_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_floor_red_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_green_wall_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen5_green_wall_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_orange_platform {
            get {
                object obj = ResourceManager.GetObject("keen5_orange_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_pink_platform {
            get {
                object obj = ResourceManager.GetObject("keen5_pink_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_pipe_platform {
            get {
                object obj = ResourceManager.GetObject("keen5_pipe_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_blue_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_blue_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_blue_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_blue_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_blue_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_blue_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_green_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_green_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_green_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_green_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_green_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_green_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_red_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_red_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_red_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_red_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_platform_red_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_platform_red_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_red_floor_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen5_red_floor_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_red_wall_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen5_red_wall_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_left_edge_black {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_left_edge_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_left_edge_filled_black {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_left_edge_filled_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_left_edge_filled_green {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_left_edge_filled_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_left_edge_filled_red {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_left_edge_filled_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_left_edge_green {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_left_edge_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_left_edge_red {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_left_edge_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_right_edge_black {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_right_edge_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_right_edge_filled_black {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_right_edge_filled_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_right_edge_filled_green {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_right_edge_filled_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_right_edge_filled_red {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_right_edge_filled_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_right_edge_green {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_right_edge_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_removable_platform_right_edge_red {
            get {
                object obj = ResourceManager.GetObject("keen5_removable_platform_right_edge_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_single_platform_blue {
            get {
                object obj = ResourceManager.GetObject("keen5_single_platform_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_single_platform_red {
            get {
                object obj = ResourceManager.GetObject("keen5_single_platform_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_black_bottom {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_black_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_black_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_black_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_black_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_black_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_black_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_black_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_green_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_green_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_green_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_green_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_green_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_green_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_red_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_red_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_red_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_red_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen5_wall_red_middle {
            get {
                object obj = ResourceManager.GetObject("keen5_wall_red_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_down {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_down_left {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_down_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_down_right {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_down_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_right {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_up {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_up_left {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_up_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_bip_platform_up_right {
            get {
                object obj = ResourceManager.GetObject("keen6_bip_platform_up_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_claw_platform {
            get {
                object obj = ResourceManager.GetObject("keen6_claw_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_claw_platform_arm {
            get {
                object obj = ResourceManager.GetObject("keen6_claw_platform_arm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_ceiling1 {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_ceiling1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_ceiling2 {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_ceiling2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_ceiling3 {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_ceiling3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_platform_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_platform_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_platform_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_platform_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_platform_middle {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_platform_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_platform_single {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_platform_single", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_wall_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_wall_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_wall_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_wall_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_wall_middle1 {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_wall_middle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_wall_middle2 {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_wall_middle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_dome_wall_to_platform {
            get {
                object obj = ResourceManager.GetObject("keen6_dome_wall_to_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_ceiling1 {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_ceiling1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_ceiling2 {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_ceiling2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_wall_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_wall_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_wall_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_wall_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_wall_middle1 {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_wall_middle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_forest_wall_middle2 {
            get {
                object obj = ResourceManager.GetObject("keen6_forest_wall_middle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_ceiling {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_ceiling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_floor_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_floor_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_floor_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_floor_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_floor_middle {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_floor_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_platform_middle {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_platform_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_platform_right {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_platform_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_single_masked_platform {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_single_masked_platform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_wall_edge_left {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_wall_edge_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_wall_edge_right {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_wall_edge_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_wall_middle {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_wall_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_industrial_wall_to_platform_left {
            get {
                object obj = ResourceManager.GetObject("keen6_industrial_wall_to_platform_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_forest_left_edge {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_forest_left_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_forest_left_edge_filled {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_forest_left_edge_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_forest_right_edge {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_forest_right_edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_forest_right_edge_filled {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_forest_right_edge_filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_left_edge_dome {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_left_edge_dome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_left_edge_filled_dome {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_left_edge_filled_dome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_right_edge_dome {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_right_edge_dome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keen6_removable_platform_right_edge_filled_dome {
            get {
                object obj = ResourceManager.GetObject("keen6_removable_platform_right_edge_filled_dome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_gem_inventory {
            get {
                object obj = ResourceManager.GetObject("red_gem_inventory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
